import { LogOut, Sparkles, Lock, Calendar, Users, TrendingUp, Target } from 'lucide-react';
import { useAuth } from './AuthProvider';
import Logo from './Logo';

export default function Dashboard() {
  const { user, signOut } = useAuth();

  const comingSoonFeatures = [
    {
      icon: Target,
      title: 'AI Workout Plans',
      description: 'Personalized workout routines generated by AI based on your goals',
      color: 'from-orange-500 to-red-500'
    },
    {
      icon: Sparkles,
      title: 'AI Meal Plans',
      description: 'Custom meal plans with macro calculations for your transformation',
      color: 'from-red-500 to-pink-500'
    },
    {
      icon: Users,
      title: 'Daily Accountability Partner',
      description: 'Get matched with someone who complements your fitness journey',
      color: 'from-pink-500 to-purple-500'
    },
    {
      icon: TrendingUp,
      title: 'Progress Tracking',
      description: 'Track weight, measurements, workouts, and see your transformation',
      color: 'from-purple-500 to-blue-500'
    },
    {
      icon: Calendar,
      title: 'Smart Scheduling',
      description: 'AI schedules your workouts and meals based on your routine',
      color: 'from-blue-500 to-teal-500'
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-red-50">
      <nav className="bg-white shadow-sm border-b">
        <div className="container mx-auto px-6 py-4 flex justify-between items-center">
          <Logo size={32} showText={true} />
          <div className="flex items-center space-x-4">
            <div className="text-right">
              <p className="text-sm text-gray-600">Welcome back!</p>
              <p className="font-semibold">{user?.user_metadata?.full_name || user?.email}</p>
            </div>
            {user?.user_metadata?.avatar_url && (
              <img
                src={user.user_metadata.avatar_url}
                alt="Profile"
                className="w-10 h-10 rounded-full border-2 border-orange-200"
              />
            )}
            <button
              onClick={signOut}
              className="flex items-center space-x-2 px-4 py-2 bg-gray-100 hover:bg-gray-200 rounded-lg transition"
            >
              <LogOut className="w-4 h-4" />
              <span>Sign Out</span>
            </button>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-6 py-12">
        <div className="max-w-6xl mx-auto">
          <div className="bg-gradient-to-r from-orange-600 to-red-600 rounded-3xl p-8 md:p-12 text-white mb-12 shadow-2xl">
            <div className="flex items-center space-x-3 mb-4">
              <Sparkles className="w-8 h-8" />
              <h1 className="text-4xl font-bold">Your Spot is Secured!</h1>
            </div>
            <p className="text-xl opacity-90 mb-6">
              Thank you for joining ReddyFit Club. Your feedback helps us build the perfect fitness transformation platform.
            </p>
            <div className="bg-white/20 backdrop-blur rounded-xl p-6">
              <p className="text-lg font-semibold mb-2">What's Next?</p>
              <ul className="space-y-2 text-sm">
                <li className="flex items-center space-x-2">
                  <div className="w-1.5 h-1.5 bg-white rounded-full"></div>
                  <span>We're analyzing your responses to personalize your experience</span>
                </li>
                <li className="flex items-center space-x-2">
                  <div className="w-1.5 h-1.5 bg-white rounded-full"></div>
                  <span>You'll get early access to features as we launch them</span>
                </li>
                <li className="flex items-center space-x-2">
                  <div className="w-1.5 h-1.5 bg-white rounded-full"></div>
                  <span>Watch your email for exclusive updates and beta invites</span>
                </li>
              </ul>
            </div>
          </div>

          <div className="mb-8">
            <h2 className="text-3xl font-bold mb-2">Coming Soon</h2>
            <p className="text-gray-600">Features we're building just for you</p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {comingSoonFeatures.map((feature, index) => (
              <div
                key={index}
                className="bg-white rounded-2xl p-6 shadow-lg hover:shadow-2xl transition transform hover:-translate-y-1 border-2 border-gray-100"
              >
                <div className="flex items-center justify-between mb-4">
                  <div className={`bg-gradient-to-br ${feature.color} w-12 h-12 rounded-xl flex items-center justify-center`}>
                    <feature.icon className="w-6 h-6 text-white" />
                  </div>
                  <div className="bg-orange-100 text-orange-600 text-xs font-bold px-3 py-1 rounded-full flex items-center space-x-1">
                    <Lock className="w-3 h-3" />
                    <span>SOON</span>
                  </div>
                </div>
                <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
                <p className="text-gray-600 text-sm leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>

          <div className="mt-12 bg-white rounded-2xl p-8 shadow-lg text-center">
            <h3 className="text-2xl font-bold mb-4">Stay Connected</h3>
            <p className="text-gray-600 mb-6">
              Follow us on social media for behind-the-scenes updates, fitness tips, and launch announcements
            </p>
            <div className="flex justify-center space-x-4">
              <a href="#" className="w-12 h-12 bg-gradient-to-br from-pink-500 to-orange-500 rounded-full flex items-center justify-center text-white hover:shadow-lg transition transform hover:scale-110">
                <span className="text-xl">📷</span>
              </a>
              <a href="#" className="w-12 h-12 bg-gradient-to-br from-blue-500 to-blue-600 rounded-full flex items-center justify-center text-white hover:shadow-lg transition transform hover:scale-110">
                <span className="text-xl">𝕏</span>
              </a>
              <a href="#" className="w-12 h-12 bg-gradient-to-br from-blue-600 to-blue-700 rounded-full flex items-center justify-center text-white hover:shadow-lg transition transform hover:scale-110">
                <span className="text-xl">in</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
